### ISSUE TITLE
Best practices for backup of data and configuration for Decko?

### ISSUE THREAD

**Issue by tukanos** [decko-commons/decko#159]
Hi Ethan,

Is there a recommended approach to periodic backup of data and configuration for Decko?  

I would like to have a cron job to backup all the data and send it to different location and have it restored there, to make sure nothing is lost.  Do you see any issues when e.g. upgrading to new version and having previous version backup?

How do you currently do it at your deployment?

**Comment by ethn** [comment]
There are basically two things to back up: your database and your uploaded files. There are different backups in place for different decks because of different sizes / configurations (some of which have files on cloud servers, for example), but all of them involve:
1. dumping and compressing the database
2. zipping and compressing the uploaded files (by default the `files` directory in your deck root.)

The simplest version is a cron job that does both locally, but of course, a better backup system will also make a copy remotely. And you'll mostly want some sort of rotation system to keep your backups from eating up too much space.
