### ISSUE TITLE
Make editor configurable to use TincyMCE instead of ProseMirror

### ISSUE THREAD

**Issue by JBetz** [decko-commons/decko#163]
ProseMirror doesn't work for my most active user, so I need to be able to configure my decko to use the old editor, TinyMCE.

This was supposedly almost ready eight months ago, but last I heard, it still hasn't been released.

On 6/5/2017 11:20 AM, Ethan McCutchen wrote:
> I don't think we finished making that configurable, but I think that's something we could add quickly, because Philipp has already done the heavy lifting.

**Comment by ethn** [comment]
It's released. Sorry, I had intended to reach out to let you  know. That was 0.3.4, at which point we actually made tinyMCE the default editor again.

But it can be configured in config/application.rb with config.rich_text_editor.

 https://github.com/decko-commons/decko/releases/tag/v0.3.4

**Comment by xithan** [comment]
A little more details:
`config.rich_text_editor = :tinymce` is the line to change the default editor which isn't necessary since the default for the default editor config is tinyMCE. Other options are `:ace`, `:prosemirror`, `:text_area` and `:text_field`.
You can check the card `*input` to see all rules that overwrite the default editor.

**Comment by ethn** [comment]
I think we can close this, yes?
