### ISSUE TITLE
[Search] Keyword parameters in Search broken again

### ISSUE THREAD

**Issue by Nemquae** [decko-commons/decko#180]
This is a followup to [this](http://wagn.org/Nested_keyword_in_Search_Fails) support ticket.

I confirmed that this was working in an earlier version, but it appears to be broken now.  An example wql search would be:

{"type":"Game Entry", "match":"$keyword", "append":"General", "sort":"relevance", "view":"closed"}

And the URL would be:

http://learning.sd.polyu.edu.hk/gamesdb/General_Search?utf8=%E2%9C%93&_keyword=RPG

The expected output would be all +General cards on Game Entry cards that match the "RPG" keyword.

The actual output is the list of all +General cards on Game Entry cards (regardless of keyword).

This was the feature that motivated us to update to Decko, so it's fairly critical that we get it back as soon as possible.

Edit:  Oh, and this is updated to the latest release.  Thanks for the help before, btw!

**Comment by Nemquae** [comment]
Sure, thanks.  I'll wait.  Enjoy your trip!

**Comment by ethn** [comment]
OK, this is fixed in 0.4.0, but the API is slightly different.

We weren't comfortable committing to the underscore variable as a general pattern (seemed a bit of a big land grab for a fairly narrow piece of the API).  So we went with something closer to rails (and decko) convention: `?_keyword=X` should become `?query[keyword]=X`.

By the way, if you're doing patterned searches, you can also consider something like this:

`/RPG+game_entries`

You do this by making a structure rule for cards ending in +game_entries (`game entry+*right+*structure`).  Make it search for

```
{ "type":"Game Entry", "match":"_left" .....}
```
... or something like that.
