### ISSUE TITLE
[card management] Error while deleting a card

### ISSUE THREAD

**Issue by tukanos** [decko-commons/decko#183]
Hi Ethan and others I don't know yet,

I know I look like the one breaking your Decko, but really I'm only trying to use it.  My friend always tells me, I'm a bug magnet.

I've tried to delete the pointer card and got this error:

![image](https://user-images.githubusercontent.com/731154/37143168-94bdf690-22ba-11e8-84d0-e4d48fb35f3b.png)

In this case in the log I got some messages:

[production.log](https://github.com/decko-commons/decko/files/1792504/production.log)

**Comment by ethn** [comment]
Thanks for this catch.  We fixed this in https://github.com/decko-commons/decko/releases/tag/v0.4.0

The issue, fwiw, was specific to deletions in ajax, which use a bit of rails api that was altered in Rails 5. So this has evidently been broken since then. There's a test for it now, though, so it should stay fixed!
