### ISSUE TITLE
Confusing web presence makes Wagn/Decko look semi-defunct 

### ISSUE THREAD

**Issue by patogit** [decko-commons/decko#287]
Hey folks, I used Wagn back in 2011 and really liked it (together with Peter K.). Now I'm checking back in on the project, and the only place I see clear action is here on GitHub. I see a bit of action on the [support ticket page](https://decko.org/Support_Ticket), but the last answer to a ticket was June 2017. Both of the mailing lists and the Twitter account seem abandoned. All of these things are pointed to from the decko.org website. All this leaves the project looking a bit abandoned. Maybe the public image of Decko could improve by reviving those communication tools, or removing them from the decko.org website, or creating a blog that reflects at least the GitHub activity. Why does the public image matter? Because software changes, and projects that look abandoned attract fewer users. Or maybe there's something else going on here that I don't understand?

**Comment by ethn** [comment]
Hi @patogit,

Very cool of you to take the time to send this thoughtful note. The short response is that we've intentionally gone a bit quiet from a communications standpoint in the past few years, but we're re-emerging now. 

The new decko.org homepage is not quite two months old, and we'll be putting a lot more attention on the rest of the site soon. As you suggested, I quickly edited away references to twitter and the mailing list and adding a couple more references to github.  We'll go a lot further soon, but those are low hanging fruit.

What's really different now is that Decko is now more than a collaborative website tool; it's a web development platform that _starts_ with collaborative websites.  As we made that transition and focused on our flagship site, Wikirate.org, we didn't want to spend a lot of energy promoting the old versions, which weren't heavily adopted and would only cause more headaches if their adoption grew too soon.

But as you imply, Decko won't ever really thrive unless it develops a much broader community – in part by showing activity.  We now have much better ways for folks to get involved, because they can build _mods_ without having to learn their way around the entire decko core.  Our next step will be to dive into engaging developers around exactly that.
