### ISSUE TITLE
Adding a not yet existing card and change the type when clicking "add card" is not possbile

### ISSUE THREAD

**Issue by remcohh** [decko-commons/decko#293]
Tried to follow the tutorial video's:

Created a parent card and added a child card like {{+some child}}
When I save the parent card I get a link `Add +some child` Clicking it creates a new card but I can only add content, I cannot change the type to image like in the instruction video

**Comment by ethn** [comment]
Good catch. That's one of many reasons why we need to update the video.  That pattern still works when nesting a simple card (meaning a card with no "+" in the name), but we stopped using it with patterned cards, because we found the name usually determined the type.

Do you need that UI, or are you just wanting a more consistent tutorial?

**Comment by GerryG** [comment]
Maybe we could make this UI available when the type is not pre-determined? Of course, you can put the type in the view options, or change it after creation. Is this controlled by default view options or triggered by the simple? test. If it is an option, the link could tell it to provide the type change UI. Mostly, you want to just tell it the type, so that maybe isn't actually useful, but it might be available already.

**Comment by ethn** [comment]
You can make a mod for that.
